project:
  type: website
  output-dir: docs

website:
  title: "R Project Sprint 2026"
  navbar:
    left: 
      - href: code-of-conduct.qmd
        text: Code of Conduct
      - href: participants/index.qmd
        text: Participants 
      - href: schedule.qmd
        text: Schedule  
      - href: travel.qmd
        text: Travel  
    right:
      - icon: mastodon
        href: https://mastodon.cloud/tags/RSprint2026
      - icon: github
        href: https://github.com/r-devel/r-project-sprint-2026
  site-url: https://contributor.r-project.org/r-project-sprint-2026
  favicon: media/favicon.png

format:
  html:
    css: styles.css
    link-external-newwindow: true
    toc: true  
    email-obfuscation: references

editor: visual

execute:
  freeze: auto



