---
title: "Travel"
---

## Arrival

Please be aware that August 29 - 31 is a bank holiday weekend, so Birmingham 
city centre will be busy and public transport may be disrupted. On the Monday,
many places will operate Sunday opening times or be closed - in particular, 
most university buildings will be closed.

### Travel to the accommodation

Participants arriving at Birmingham airport are recommended to take the 
free Air-Rail Link monorail to Birmingham International train station, then 
catch a train to Birmingham New Street (single ticket £5.00 from the ticket 
machines at the station). 

Then catch an X20/X21/X22 bus from 
St Martin's Queensway (Stop NS3) between the station and the Bullring shopping 
centre (tap the payment machine with your contactless card/phone as you get on 
the bus, you'll be charged £3 for each single journey up to a daily cap of 
£5.50).

Stops are usually displayed on the bus and also have these names on Google maps. 
Get off at

* Aston House stop for Chamberlain Hall (reception closes at 10pm)
* Vale Village stop for the Shackleton Building to check-in to Chamberlain Hall 
after 10pm (reception open 24 hours)
* Westmere stop for Peter Scott House/Edgbaston Park Hotel

Total journey time should be around 50 minutes. Trains and buses do run until 
late at night, but you may prefer Uber/Bolt from the airport in this case, 
which will take around 30 minutes and cost around £30.

### Arriving at Chamberlain Hall

Check in is from 4pm. If you arrive earlier, you can store your luggage at 
Chamberlain Hall. The accommodation is next to a small park with a lake that 
is a nice place to wait a  while if the weather is nice. Otherwise you 
can walk to the Shackleton building, go in at reception and keep walking towards 
"The Shack" a lounge/canteen where there are tables and chairs you can use (a 
few plugs if you search hard enough). There are two outlets:

* Costcutter (Sunday only, 12pm-6pm): a mini supermarket
* "Coffee & hot food" (Monday only, 10am-3pm): to find this cafe, keep walking 
through The Shack, go out the door at the other end and walk towards the doors 
to the outside - the cafe is on your right and there are some nice booth seats 
to your left.

You might also walk to the Edgbaston Park Hotel, see the next section.

### Arriving at Edgbaston Park Hotel/Peter Scott House

Check-in is at Edgbaston Park Hotel for both hotels from 2pm, you can store 
your luggage there. 

If you arrive early, you are recommended to wait in the cafe bar/lounge that is 
just beyond reception. There are plenty of plugs to charge up your laptop or 
phone. The bar opens at 9am, food is available from the bar menu:
breakfast from 9:30am-12pm, sandwiches 12pm-6:30pm, and salads, pizza and other 
main dishes from 12pm-9pm. Expect to pay £15-25 for a meal.

If you arrive earlier, or want something a bit cheaper, you can go to 
[Joe's](https://www.guildofstudents.com/joes/), a Wetherspoon's pub on campus 
that is open 8am-midnight.

## Travel to Sprint Venue (PHTA)

The sprint will be held at the [Precision Health Technologies Accelerator (PHTA), on the Birmingham Health Innovation Campus, post code B29 6TH](https://campusmap.bham.ac.uk/search/5d6f492e1e1f64009327b6db?projectId=uob). 
Google maps knows it as PHTA, for other apps use the post code.

### Bus (recommended)

People staying at Chamberlain Hall, Edgbaston Park Hotel and Peter Scott House 
are recommended to travel by bus. 
Stops are usually displayed on the bus and also have these names on Google maps. 

#### Chamberlain Hall

Get the **X20** or **X21** bus from the Vale Village stop (closest stop to the breakfast venue) 
and get off at The Oleaster stop [(full directions from breakfast venue to sprint)](https://www.google.com/maps/dir/Vale+Village,+Birmingham+B15+2RE/PHTA,+Selly+Oak,+Birmingham+B29+6TH/@52.4519548,-1.942407,15z/data=!3m1!4b1!4m20!4m19!1m5!1m1!1s0x4870bc4c7cf2cbaf:0x3f2da2a3fffd5a9d!2m2!1d-1.925999!2d52.458099!1m5!1m1!1s0x4870bd083003471d:0x7cb997b3f3cf89fe!2m2!1d-1.9389699!2d52.4458031!2m4!4e3!6e1!7e2!8j1788253200!3e3!5i2?entry=ttu&g_ep=EgoyMDI2MDgyNi4wIKXMDSoASAFQAw%3D%3D), **journey time 25 minutes**.

Getting the **X22** from Vale Village is also possible, but you need to get off 
at the University Station stop and walk from there, which takes a few more minutes.

#### Edgbaston Park Hotel/Peter Scott House 

Get the **X20** or **X21** from Westmere (bus stop on the road outside the hotel) 
and get off at The Oleaster stop [(full directions from the hotel to the sprint)](https://www.google.com/maps/dir/Edgbaston+Park+Hotel+and+Conference+Centre,+53+Edgbaston+Park+Rd,+Birmingham+B15+2RS/PHTA,+Selly+Oak,+Birmingham+B29+6TH/@52.4502595,-1.942407,15z/data=!3m1!4b1!4m19!4m18!1m5!1m1!1s0x4870bc4af1ef4715:0x7405976418d394d1!2m2!1d-1.9271455!2d52.453993!1m5!1m1!1s0x4870bd083003471d:0x7cb997b3f3cf89fe!2m2!1d-1.9389699!2d52.4458031!2m4!4e3!6e1!7e2!8j1788253200!3e3?entry=ttu&g_ep=EgoyMDI2MDgyNi4wIKXMDSoASAFQAw%3D%3D), **journey time 15 minutes**.

Getting the **X22** from the Westmere bus stop is also possible, but you need to get off 
at the University Station stop and walk from there, which takes a few more minutes.

### Walking

#### Chamberlain Hall

Directions are given from the breakfast venue as it is closer - still a long walk though!

* [Route 1 via canal](www.google.com/maps/dir/Edgbaston+Park+Hotel+and+Conference+Centre,+53+Edgbaston+Park+Rd,+Birmingham+B15+2RS/PHTA,+Selly+Oak,+Birmingham+B29+6TH/@52.449921,-1.9376593,16z/data=!3m1!4b1!4m19!4m18!1m5!1m1!1s0x4870bc4af1ef4715:0x7405976418d394d1!2m2!1d-1.9271455!2d52.453993!1m5!1m1!1s0x4870bd083003471d:0x7cb997b3f3cf89fe!2m2!1d-1.9389699!2d52.4458031!2m4!4e3!6e1!7e2!8j1788253200!3e2?entry=ttu&g_ep=EgoyMDI2MDgyNi4wIKXMDSoASAFQAw%3D%3D), 36 minutes, simple and mostly off-road.
* [Route 2 via university](www.google.com/maps/dir/Edgbaston+Park+Hotel+and+Conference+Centre,+53+Edgbaston+Park+Rd,+Birmingham+B15+2RS/PHTA,+Selly+Oak,+Birmingham+B29+6TH/@52.449921,-1.9376593,16z/data=!3m1!4b1!4m19!4m18!1m5!1m1!1s0x4870bc4af1ef4715:0x7405976418d394d1!2m2!1d-1.9271455!2d52.453993!1m5!1m1!1s0x4870bd083003471d:0x7cb997b3f3cf89fe!2m2!1d-1.9389699!2d52.4458031!2m4!4e3!6e1!7e2!8j1788253200!3e2?entry=ttu&g_ep=EgoyMDI2MDgyNi4wIKXMDSoASAFQAw%3D%3D), 36 minutes, more roads to cross but still mostly off-road and can explore the campus a bit.

#### Edgbaston Park Hotel/Peter Scott House 

Google maps will give you various options walking along roads - simple but less interesting! Route 1 is just as quick and Route 2 diverts round the historic part of the university:

* [Route 1 via green heart](https://www.google.com/maps/dir/Edgbaston+Park+Hotel+and+Conference+Centre,+53+Edgbaston+Park+Rd,+Birmingham+B15+2RS/PHTA,+Selly+Oak,+Birmingham+B29+6TH/@52.4507961,-1.9317999,17.69z/data=!4m29!4m28!1m15!1m1!1s0x4870bc4af1ef4715:0x7405976418d394d1!2m2!1d-1.9271455!2d52.453993!3m4!1m2!1d-1.9309166!2d52.4518237!3s0x4870bdca9a1c8743:0x7d1053e04be8598a!3m4!1m2!1d-1.9316454!2d52.4504084!3s0x4870bdca5bdc2c29:0x741c0ee2ee055961!1m5!1m1!1s0x4870bd083003471d:0x7cb997b3f3cf89fe!2m2!1d-1.9389699!2d52.4458031!2m4!4e3!6e1!7e2!8j1788253200!3e2?entry=ttu&g_ep=EgoyMDI2MDgyNi4wIKXMDSoASAFQAw%3D%3D), 23 minutes
* [Route 2 via Old Joe](www.google.com/maps/dir/Edgbaston+Park+Hotel+and+Conference+Centre,+53+Edgbaston+Park+Rd,+Birmingham+B15+2RS/PHTA,+Selly+Oak,+Birmingham+B29+6TH/@52.449921,-1.9376593,16z/data=!3m1!4b1!4m19!4m18!1m5!1m1!1s0x4870bc4af1ef4715:0x7405976418d394d1!2m2!1d-1.9271455!2d52.453993!1m5!1m1!1s0x4870bd083003471d:0x7cb997b3f3cf89fe!2m2!1d-1.9389699!2d52.4458031!2m4!4e3!6e1!7e2!8j1788253200!3e2?entry=ttu&g_ep=EgoyMDI2MDgyNi4wIKXMDSoASAFQAw%3D%3D), 26 minutes



## Local Shops

* [Edgbaston Co-op](https://www.coop.co.uk/store-finder/B15-2LJ/wheeleys-road) mid-size supermarket 10 minutes walk from Chamberlain Hall, open 7am-10pm daily.
* [University Co-op](https://www.coop.co.uk/store-finder/B15-2TT/1st-floor-university-centre) mini supermarket 10 minutes walk from Edgbaston Park Hotel/Peter Soctt House, open 9am-5pm Sunday, 7am-10pm Monday-Saturday.
* [Selly Oak Shops](https://sellyoakshoppingpark.co.uk/) retail park with a variety of shops and cafés, including Sainsbury’s (large supermarket selling clothing as well as food, toiletries, medicine, etc), Superdrug (pharmacy/chemist), Argos (homeware/tech, e.g. if you forgot your UK plug adapter!), Starbucks, Mcdonalds, etc. This is 2-minutes walk from the sprint venue, so follow instructions to 
travel to the venue.

## Things to Do

If you want something to do before the sprint, here are a few suggestions:

* [Birmingham Weekender](https://www.birminghamhippodrome.com/birmingham-weekender-2026-whats-on/) 
free festival of music and dance, across city centre venues (including New Street Station!)
* [Winterbourne House](https://www.winterbourne.org.uk) an Arts and Crafts villa and garden, a short walk from Edgbaston Park Hotel. There is also a cafe here open 10:30am - 4:30pm. Entrance may be free for people staying at Edgbaston Park Hotel and Peter Scott House, please enquire at reception.
* [Midlands Arts Centre](https://macbirmingham.co.uk/) a 10 minute bus ride on the number 1 bus from Chamberlain Hall. Next to [Cannon Hill Park](https://www.cannonhillpark.co.uk/), the MAC has some free exhibitions, a cafe and an arts cinema. There will be free live jazz and soul music 1pm-4pm on Monday 31 August. 

